export type WeekData = {
  size: string;
  development: string;
};

export const babyData: Record<number, WeekData> = {
  1: { size: "Poppy seed", development: "Conception occurs. Your egg and sperm unite to form a single cell that will divide and multiply over the coming weeks." },
  2: { size: "Poppy seed", development: "Implantation may occur. The fertilized egg travels down the fallopian tube and may implant in your uterus." },
  3: { size: "Poppy seed", development: "The embryo forms. Your baby's brain, spinal cord, and heart begin to develop. The placenta starts forming." },
  4: { size: "Sesame seed", development: "Neural tube closes. The foundation for the brain and spine is complete. Tiny arm and leg buds appear." },
  5: { size: "Lentil", development: "The heart begins beating. Major organs start forming. Your baby is about 2mm long." },
  6: { size: "Sweet pea", development: "Facial features form. Eyes, nose, and ears begin to take shape. Tiny fingers develop." },
  7: { size: "Blueberry", development: "Brain develops rapidly. Elbows and toes are visible. The baby doubles in size." },
  8: { size: "Raspberry", development: "All major organs form. Bones begin to replace cartilage. Baby makes first movements." },
  9: { size: "Cherry", development: "Tiny toes visible. Eyelids form. Baby can make a fist. Heart has four chambers." },
  10: { size: "Strawberry", development: "Vital organs fully formed. Baby can swallow. Fingernails and hair follicles develop." },
  11: { size: "Lime", development: "Baby is fully formed. Genitals developing. Diaphragm practices breathing movements." },
  12: { size: "Plum", development: "Reflexes develop. Baby can open and close fingers. Vocal cords form." },
  13: { size: "Peach", development: "Unique fingerprints form. Baby can suck thumb. Intestines move into abdomen." },
  14: { size: "Lemon", development: "Fine hair (lanugo) covers body. Baby practices breathing. Neck is defined." },
  15: { size: "Apple", development: "Bones hardening. Baby can sense light. Taste buds develop." },
  16: { size: "Avocado", development: "You may feel baby move! Eyebrows and eyelashes appear. Heart pumps 25 quarts daily." },
  17: { size: "Pear", development: "Fat accumulates. Baby's skeleton turns from soft cartilage to bone." },
  18: { size: "Sweet potato", development: "Baby hears your voice. Vernix protects the skin. Kicks become stronger." },
  19: { size: "Mango", development: "Hair grows on scalp. Sensory development: taste, smell, hearing, touch, sight." },
  20: { size: "Banana", development: "Halfway there! Baby swallows regularly. Meconium forms in intestines." },
  21: { size: "Carrot", development: "Bone marrow makes blood cells. Eyebrows visible. Baby has sleep and wake cycles." },
  22: { size: "Papaya", development: "Sense of touch develops. Baby explores by touching own face and body." },
  23: { size: "Grapefruit", development: "Rapid eye movements begin. Baby can hear loud sounds. Skin is wrinkled." },
  24: { size: "Cantaloupe", development: "Lungs develop surfactant. Baby is viable with medical care. Responds to your touch." },
  25: { size: "Cauliflower", development: "Hand and startle reflexes. Baby's hands are fully developed." },
  26: { size: "Lettuce", development: "Eyes open and close. Baby responds to light. Lungs continue developing." },
  27: { size: "Cabbage", development: "Brain grows rapidly. Baby can dream during REM sleep." },
  28: { size: "Eggplant", development: "Third trimester begins. Baby can blink. More fat accumulates." },
  29: { size: "Butternut squash", development: "Bones fully developed. Baby kicks and stretches. Less room to move." },
  30: { size: "Cabbage", development: "Eyes open wide. Baby may have a full head of hair." },
  31: { size: "Coconut", development: "All five senses are working. Baby practices breathing movements." },
  32: { size: "Jicama", development: "Toenails visible. Lanugo starts to disappear. Baby gains weight rapidly." },
  33: { size: "Pineapple", development: "Pupils dilate in response to light. Bones hardening (except skull)." },
  34: { size: "Cantaloupe", development: "Central nervous system matures. Lungs nearly fully developed." },
  35: { size: "Honeydew", development: "Kidneys fully developed. Liver processes waste. Physical growth slows." },
  36: { size: "Papaya", development: "Baby takes up most of the uterus. Less movement as space tightens." },
  37: { size: "Swiss chard", development: "Early full-term! Baby is considered full-term. Lungs fully mature." },
  38: { size: "Leek", development: "Vernix and lanugo mostly gone. Baby continues gaining weight." },
  39: { size: "Watermelon", development: "Due date week! Baby's organs ready for life outside. Skull plates flexible for birth." },
  40: { size: "Watermelon", development: "Your baby is ready to meet you! Any day now. Cherish these final moments." },
};
